# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Transcribe-notes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_8ccfb791bf394f44915318d566ab8f30 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_eee5c0dde934476299444ddea3c102d5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_8ccfb791bf394f44915318d566ab8f30 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Transcribe-notes'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c5735c7bff384e758b88872d86b25f9a }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_8ccfb791bf394f44915318d566ab8f30 }}/appsvc/staticsite:${{ github.sha }}'